### PR TITLE
unify yaml files

### PR DESCRIPTION
**Pull request by YueErro**
@igorrecioh can you test this, please? Thanks!

### CODE REVIEW

**Comment by YueErro** [comment]
You will need the changes in [MARA](https://github.com/AcutronicRobotics/MARA/pull/69).

**Comment by alesolano** [comment]
Tested along with https://github.com/AcutronicRobotics/MARA/pull/69
It works for me

**Comment by igorrecioh** [comment]
Trying right now!

**Comment by igorrecioh** [comment]
Working great guys! Nice job reducing YAML files!

**Pull request merged**
